from __future__ import annotations

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL, role_query TEXT NOT NULL, title TEXT NOT NULL,
    company TEXT NOT NULL, location TEXT NOT NULL, posting_date TEXT NOT NULL,
    link TEXT NOT NULL, salary TEXT NOT NULL DEFAULT '',
    workplace_type TEXT NOT NULL DEFAULT '', employment_type TEXT NOT NULL DEFAULT '',
    applicant_count TEXT NOT NULL DEFAULT '', easy_apply INTEGER NOT NULL DEFAULT 0,
    description TEXT NOT NULL DEFAULT '', visa_assessment TEXT NOT NULL DEFAULT '',
    visa_evidence TEXT NOT NULL DEFAULT '', h1b_filings INTEGER NOT NULL DEFAULT 0,
    visa_source_url TEXT NOT NULL DEFAULT '', visa_checked_at TEXT NOT NULL DEFAULT '',
    gemini_status TEXT NOT NULL DEFAULT '', gemini_summary TEXT NOT NULL DEFAULT '',
    gemini_skills_required TEXT NOT NULL DEFAULT '[]', gemini_skills_preferred TEXT NOT NULL DEFAULT '[]',
    gemini_responsibilities TEXT NOT NULL DEFAULT '[]', gemini_requirements TEXT NOT NULL DEFAULT '[]',
    gemini_education TEXT NOT NULL DEFAULT '', gemini_experience TEXT NOT NULL DEFAULT '',
    gemini_location TEXT NOT NULL DEFAULT '', gemini_workplace_type TEXT NOT NULL DEFAULT '',
    gemini_employment_type TEXT NOT NULL DEFAULT '', gemini_visa_status TEXT NOT NULL DEFAULT '',
    gemini_visa_evidence TEXT NOT NULL DEFAULT '', gemini_error TEXT NOT NULL DEFAULT '',
    gemini_model TEXT NOT NULL DEFAULT '', gemini_analyzed_at TEXT NOT NULL DEFAULT '',
    application_status TEXT NOT NULL DEFAULT 'Saved', applied_date TEXT NOT NULL DEFAULT '',
    applied_at TEXT NOT NULL DEFAULT '', application_link TEXT NOT NULL DEFAULT '',
    application_notes TEXT NOT NULL DEFAULT '', follow_up_date TEXT NOT NULL DEFAULT '',
    local_match_score INTEGER, local_match_resume_id BIGINT,
    local_match_evidence TEXT NOT NULL DEFAULT '[]', local_match_missing TEXT NOT NULL DEFAULT '[]',
    local_match_hard_no INTEGER NOT NULL DEFAULT 0, local_match_hard_no_reasons TEXT NOT NULL DEFAULT '[]',
    local_match_analyzed_at TEXT NOT NULL DEFAULT '', local_semantic_score INTEGER,
    public_capture_metadata TEXT NOT NULL DEFAULT '{}', public_capture_status TEXT NOT NULL DEFAULT '',
    public_captured_at TEXT NOT NULL DEFAULT '', collected_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE(source, link)
);

CREATE TABLE IF NOT EXISTS resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, filename TEXT NOT NULL, content TEXT NOT NULL,
    uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS resume_job_matches (
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
    score INTEGER NOT NULL DEFAULT 0, is_best INTEGER NOT NULL DEFAULT 0,
    rationale TEXT NOT NULL DEFAULT '', matched_skills TEXT NOT NULL DEFAULT '[]',
    missing_skills TEXT NOT NULL DEFAULT '[]', improvements TEXT NOT NULL DEFAULT '[]',
    hard_no INTEGER NOT NULL DEFAULT 0, hard_no_reasons TEXT NOT NULL DEFAULT '[]',
    analyzed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    PRIMARY KEY (job_id, resume_id)
);

CREATE TABLE IF NOT EXISTS application_helpers (
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    resume_id BIGINT NOT NULL REFERENCES resumes(id) ON DELETE CASCADE,
    content TEXT NOT NULL DEFAULT '{}', model TEXT NOT NULL DEFAULT '',
    generated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    PRIMARY KEY (job_id, resume_id)
);
"""


def schema_statements() -> list[str]:
    return [statement.strip() for statement in POSTGRES_SCHEMA.split(";") if statement.strip()]
